app = "predictive-maint-system"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  REDIS_HOST = "127.0.0.1"
  OLLAMA_URL = "http://localhost:11434/api"

[[mounts]]
  source = "factory_data"
  destination = "/app/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/api/equipment"
